apiVersion: v1
kind: ConfigMap
metadata:
  name: gemini-config
  namespace: gemini-namespace
data:
  GOOGLE_ID: 905822246633-vckeb2070d1t3frob2rda37a1dk1sh.apps.googleusercontent.com  
  MONGODB_URI: mongodb://mongodb-service:27017/gemini
  NEXTAUTH_URL: https://62.72.20.156.nip.io
  MONGO_INITDB_ROOT_USERNAME: admin
