apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_SECRET: RzBDU1BYLVh4cE5MUFo5TWVoVERiWUxtalFReFVsRWY0aQ== # Base64 for g 
  NEXTAUTH_SECRET: bElwR0VnN2dMTnkwT29iZUdwRVFDbWpIVGxlUlVUVkNqdnVsb25LQ1pTOD0= 
  NEXT_PUBLIC_API_KEY: QUl6YVN5QUVpMGR0OE9GWE0tOWZTc1Q4OHRlZE9tcXgtUE1INkJJ 
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW5AMTIzCg==  # Base64 for admin@123
